name: restaurant_rating
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_maps_flutter: ^2.1.1
  get_storage: 2.0.3
  lottie: 1.2.2
  flutter_native_splash: 1.2.0
  http: 0.13.4
  cached_network_image: 3.2.0
  qr_flutter: 4.0.0
  share_plus: 3.0.5
  path_provider: 2.0.9
  permission_handler: any
  screenshot: 1.2.3
  image_picker: 0.8.4+9
  geolocator:
  qr_code_scanner:
  google_maps_controller:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/logo1.png
  ios: true

flutter_native_splash: 
  color: '#FFFFFF'
  image: assets/images/logo.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: false

flutter: 
  assets: 
    - assets/json/
    - assets/images/
  uses-material-design: true

